# Generated by Django 5.2.14 on 2026-06-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_application_resume_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='careers_app_job_id_17123a_idx',
            old_name='careers_app_job_date_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='careers_app_email_65e5d2_idx',
            old_name='careers_app_email_date_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='careers_job_status_af80ff_idx',
            old_name='careers_job_status_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='careers_job_approva_399d8d_idx',
            old_name='careers_job_approv_eb7a89_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='careers_job_area_ba78d5_idx',
            old_name='careers_job_filters_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='careers_job_area_ow_089ec3_idx',
            old_name='careers_job_area_own_302ab5_idx',
        ),
    ]
