# Generated by Django 5.2.14 on 2026-06-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_application_deleted_at_application_deletion_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compensation_type',
            field=models.CharField(choices=[('a_combinar', 'A combinar'), ('valor_salarial', 'Valor salarial'), ('pretensao_salarial', 'Pretensao salarial')], default='a_combinar', max_length=30, verbose_name='Informacao salarial'),
        ),
        migrations.AddField(
            model_name='job',
            name='compensation_value',
            field=models.CharField(blank=True, max_length=80, verbose_name='Valor ou faixa salarial'),
        ),
    ]
